package com.deray.meditation.db.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.deray.meditation.db.bean.Music;
import com.deray.meditation.db.bean.PlayList;
import com.deray.meditation.db.bean.Search;

import com.deray.meditation.db.dao.MusicDao;
import com.deray.meditation.db.dao.PlayListDao;
import com.deray.meditation.db.dao.SearchDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig musicDaoConfig;
    private final DaoConfig playListDaoConfig;
    private final DaoConfig searchDaoConfig;

    private final MusicDao musicDao;
    private final PlayListDao playListDao;
    private final SearchDao searchDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        musicDaoConfig = daoConfigMap.get(MusicDao.class).clone();
        musicDaoConfig.initIdentityScope(type);

        playListDaoConfig = daoConfigMap.get(PlayListDao.class).clone();
        playListDaoConfig.initIdentityScope(type);

        searchDaoConfig = daoConfigMap.get(SearchDao.class).clone();
        searchDaoConfig.initIdentityScope(type);

        musicDao = new MusicDao(musicDaoConfig, this);
        playListDao = new PlayListDao(playListDaoConfig, this);
        searchDao = new SearchDao(searchDaoConfig, this);

        registerDao(Music.class, musicDao);
        registerDao(PlayList.class, playListDao);
        registerDao(Search.class, searchDao);
    }
    
    public void clear() {
        musicDaoConfig.clearIdentityScope();
        playListDaoConfig.clearIdentityScope();
        searchDaoConfig.clearIdentityScope();
    }

    public MusicDao getMusicDao() {
        return musicDao;
    }

    public PlayListDao getPlayListDao() {
        return playListDao;
    }

    public SearchDao getSearchDao() {
        return searchDao;
    }

}
